version: "3"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - "./:/var/www"
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    networks: 
        - setup-docker-rails
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      RAILS_ENV: development
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes: 
      - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"
    networks: 
      - setup-docker-rails
volumes:
  gem_cache:
  db_data:
  node_modules: 
networks:
  setup-docker-rails:
    driver: bridge
